services:
  api:
    container_name: evolution_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
      - evolution-postgres
    ports:
      - "127.0.0.1:8082:8080"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - delivery-net
    env_file:
      - .env

  frontend:
    container_name: evolution_frontend
    image: evoapicloud/evolution-manager:latest
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    networks:
      - delivery-net

  redis:
    container_name: evolution_redis
    image: redis:latest
    restart: always
    command: >
      redis-server --appendonly yes
    volumes:
      - evolution_redis:/data
    networks:
      - delivery-net

  evolution-postgres:
    container_name: evolution_postgres
    image: postgres:15
    restart: always
    env_file:
      - .env
    command:
      - postgres
      - -c
      - max_connections=1000
      - -c
      - listen_addresses=*
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - delivery-net

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:

networks:
  delivery-net:
    external: true