services:

  api:
    container_name: evolution_api
    build:
      context: .
    restart: no
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - 8080
      - 9229
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first

  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis-evolution
    restart: no
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6378:6379

  postgres:
    container_name: postgres-evolution
    image: postgres:15
    networks:
      - evolution-net
    command: [
      "postgres",
      "-c", "max_connections=1000",
      "-c", "listen_addresses=*",
      "-c", "shared_buffers=256MB",
      "-c", "effective_cache_size=1GB",
      "-c", "work_mem=4MB",
      "-c", "logging_collector=on",
      "-c", "log_directory=log",
      "-c", "log_filename=postgresql.log",
      "-c", "log_statement=all",
      "-c", "log_connections=on",
      "-c", "log_disconnections=on"
    ]
    restart: no
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=evolution_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_logs:/var/log/postgresql

  rabbitmq:
    container_name: rabbitmq
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: rabbitmq:management
    networks:
      - evolution-net
    restart: no
    environment:
      - RABBITMQ_ERLANG_COOKIE=33H2CdkzF5WrnJ4ud6nkUdRTKXvbCHeFjvVL71p
      - RABBITMQ_DEFAULT_VHOST=default
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672

  # pgbouncer:
  #   image: edoburu/pgbouncer:latest
  #   environment:
  #     DB_HOST: postgres
  #     DB_USER: user
  #     DB_PASSWORD: pass
  #     POOL_MODE: transaction
  #     AUTH_TYPE: trust
  #     MAX_CLIENT_CONN: 1000
  #     DEFAULT_POOL_SIZE: 25
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "6543:5432"
  #   networks:
  #     - evolution-net

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:
  rabbitmq_data:

networks:
  evolution-net:
    name: evolution-net
    external: true
    driver: bridge
