version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
  
  rebrow:
    image: marian/rebrow
    ports: 
      - 5001:5001
    links:
      - redis

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - evolution_mongodb_data:/data/db
      - evolution_mongodb_configdb:/data/configdb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    expose:
      - 27017

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - 8081:8081
    links:
      - mongodb
  api:
    container_name: evolution_api
    image: evolution/api:local
    restart: always
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    env_file:
      - ./Docker/.env
    command: ['node', './dist/src/main.js']
    expose:
      - 8080
    links:
      - mongodb
      - redis

volumes:
  evolution_instances:
  evolution_store:
  evolution_mongodb_data:
  evolution_mongodb_configdb:
  evolution_redis:

networks:
  default:
    name: evolution-net
  