version: "3.8"

services:
  api:
    container_name: evolution_api
    build:
      context: .
      dockerfile: Dockerfile
    image: evolution-api:vps
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net

  postgres:
    container_name: evolution_postgres
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution-net

  redis:
    container_name: evolution_redis
    image: redis:7
    restart: always
    command: redis-server --port 6379 --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - evolution-net

volumes:
  evolution_instances:
  postgres_data:
  redis_data:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge

